version: "3.9"

x-logging: &logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        command: poetry run app
        volumes:
            - "./src/:/app/src"
        depends_on:
            - mongo
        ports:
            - "8993:${APP_DEFAULT_PORT}"
        env_file:
            - ./dotenv/app.env
        logging: *logging

    mongo:
        image: mongo:7.0.12
        restart: always
        environment:
            MONGO_DB: "${MONGO_DB}"
            MONGO_USER: "${MONGO_USER}"
            MONGO_PASSWORD: "${MONGO_PASSWORD}"
            MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
            MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
        ports:
            - "27040:${MONGO_PORT}"
        volumes:
            - trailhub_data:/data/db
        env_file:
            - ./dotenv/mongo.env
        logging: *logging

volumes:
    trailhub_data:
